server:
  port: 3000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tree
    username: tree
    password: 1234
  jpa:
    database: POSTGRESQL
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true

#  google email 인증보내기 sample
  mail:
    host: smtp.gmail.com
    port: 587
    username: blackduvet52@gmail.com
    password: xgcqsjdewmorjvqb
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

# JWT Secret ??
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK